In [3]:
import pandas as pd

In [12]:
riskforecasting = pd.read_csv('~data/prf.csv')
riskforecasting["riskLevelLabel"].replace({"normal": 0, "increased": 1}, inplace=True)
riskforecasting['time'] = pd.to_datetime(riskforecasting['predictedAt']).dt.strftime('%Y-%m-%d')
riskforecasting.drop(['label', 'predictedAt', 'publishedAt', 'expiresAt', 'warning'], axis=1, inplace=True)
riskforecasting.rename({'EUBWID':'site'}, axis=1, inplace=True)
riskforecasting = riskforecasting[riskforecasting['riskLevelLabel'] != 'no-prediction']
riskforecasting = riskforecasting.groupby(['site', 'time'])['riskLevelLabel'].max().reset_index()
riskforecasting

                 site        time  riskLevelLabel
0       ukc1101-06000  2020-05-14               0
1       ukc1101-06000  2020-05-15               0
2       ukc1101-06000  2020-05-16               0
3       ukc1101-06000  2020-05-17               0
4       ukc1101-06000  2020-05-18               0
...               ...         ...             ...
207057  ukk4307-33900  2023-06-08               0
207058  ukk4307-33900  2023-06-09               0
207059  ukk4307-33900  2023-06-10               0
207060  ukk4307-33900  2023-06-11               0
207061  ukk4307-33900  2023-06-12               0

[207062 rows x 3 columns]

In [13]:
riskforecasting.to_csv('~data/pollution_risk_forecasting.csv', index=False)