In [2]:
import pandas as pd

In [9]:
riskforecasting = pd.read_csv('~data/pollution_risk_forecasting_raw.csv')
riskforecasting = riskforecasting[['label', 'predictedAt', 'warning', 'riskLevelLabel']]
riskforecasting.columns = ['site', 'time', 'warning', 'riskLevel']
riskforecasting['time'] = pd.to_datetime(riskforecasting['time']).dt.date
riskforecasting

,site,time,warning,riskLevel
0,Seaton Carew North,2022-04-28,Pollution RIsk Forecasts will start soon,normal
1,Seaton Carew North,2022-04-29,Pollution RIsk Forecasts will start soon,normal
2,Seaton Carew North,2022-04-30,Pollution RIsk Forecasts will start soon,normal
3,Seaton Carew North,2022-05-04,No warnings in place,normal
4,Seaton Carew North,2022-05-05,No warnings in place,normal
...,...,...,...,...
66609,Westward Ho!,2023-04-29,Pollution RIsk Forecasts will start soon,normal
66610,Westward Ho!,2023-04-30,Pollution RIsk Forecasts will start soon,normal
66611,Westward Ho!,2023-05-01,No pollution incidents reported,normal
66612,Westward Ho!,2023-05-02,No pollution incidents reported,normal
66613,Westward Ho!,2023-05-03,No pollution incidents reported,normal

In [10]:
riskforecasting = riskforecasting.sort_values(by=['site', 'time', 'riskLevel'], ascending=[True, True, True])
riskforecasting = riskforecasting.drop_duplicates(subset=['site', 'time'], keep='first')
riskforecasting.reset_index(drop=True, inplace=True)
riskforecasting

,site,time,warning,riskLevel
0,Ainsdale,2022-04-28,Pollution RIsk Forecasts will start soon,normal
1,Ainsdale,2022-04-29,Pollution RIsk Forecasts will start soon,normal
2,Ainsdale,2022-04-30,Pollution RIsk Forecasts will start soon,normal
3,Ainsdale,2022-05-04,No warnings in place,normal
4,Ainsdale,2022-05-05,No warnings in place,normal
...,...,...,...,...
66558,Yaverland,2023-04-29,Pollution RIsk Forecasts will start soon,normal
66559,Yaverland,2023-04-30,Pollution RIsk Forecasts will start soon,normal
66560,Yaverland,2023-05-01,No pollution incidents reported,normal
66561,Yaverland,2023-05-02,No pollution incidents reported,normal
66562,Yaverland,2023-05-03,No pollution incidents reported,normal

In [11]:
riskforecasting.to_csv('~data/pollution_risk_forecasting_cleaned.csv', index=False)