In [1]:
import pandas as pd

In [2]:
riskforecasting = pd.read_csv('~data/pollution_risk_forecasting_raw.csv')
riskforecasting = riskforecasting[['label', 'predictedAt', 'warning', 'riskLevelLabel']]
riskforecasting.columns = ['site', 'time', 'warning', 'riskLevelLabel']
riskforecasting['time'] = pd.to_datetime(riskforecasting['time']).dt.date
riskforecasting

,site,time,warning,riskLevelLabel
0,Seaton Carew North,2022-04-28,Pollution RIsk Forecasts will start soon,normal
1,Seaton Carew North,2022-04-29,Pollution RIsk Forecasts will start soon,normal
2,Seaton Carew North,2022-04-30,Pollution RIsk Forecasts will start soon,normal
3,Seaton Carew North,2022-05-04,No warnings in place,normal
4,Seaton Carew North,2022-05-05,No warnings in place,normal
...,...,...,...,...
69588,Westward Ho!,2023-05-06,No pollution incidents reported,normal
69589,Westward Ho!,2023-05-07,No pollution incidents reported,normal
69590,Westward Ho!,2023-05-08,No pollution incidents reported,normal
69591,Westward Ho!,2023-05-09,No pollution incidents reported,normal
69592,Westward Ho!,2023-05-10,No pollution incidents reported,normal

In [3]:
riskforecasting = riskforecasting.sort_values(by=['site', 'time', 'riskLevelLabel'], ascending=[True, True, True])
riskforecasting = riskforecasting.drop_duplicates(subset=['site', 'time'], keep='first')
riskforecasting.reset_index(drop=True, inplace=True)
riskforecasting

,site,time,warning,riskLevelLabel
0,Ainsdale,2022-04-28,Pollution RIsk Forecasts will start soon,normal
1,Ainsdale,2022-04-29,Pollution RIsk Forecasts will start soon,normal
2,Ainsdale,2022-04-30,Pollution RIsk Forecasts will start soon,normal
3,Ainsdale,2022-05-04,No warnings in place,normal
4,Ainsdale,2022-05-05,No warnings in place,normal
...,...,...,...,...
69533,Yaverland,2023-05-06,No pollution incidents reported,normal
69534,Yaverland,2023-05-07,No pollution incidents reported,normal
69535,Yaverland,2023-05-08,No pollution incidents reported,normal
69536,Yaverland,2023-05-09,No pollution incidents reported,normal
69537,Yaverland,2023-05-10,No pollution incidents reported,normal

In [4]:
riskforecasting.to_csv('~data/pollution_risk_forecasting.csv', index=False)